site_name: ADHD Info Dump
site_description: ADHD Info Dump
site_author: polite raccoon
site_url: https://polite-raccoon.github.io/adhd-info-dump/
repo_name: 'polite-raccoon/adhd-info-dump'
repo_url: 'https://github.com/polite-raccoon/adhd-info-dump'
plugins:
  - search
  - autorefs
  - git-revision-date-localized
  - enumerate-headings
theme:
  features:
    - tabs
    - navigation.expand
    - navigation.sections
    - toc.follow
  name: material
  icon:
    logo: material/hexagon-multiple
  font:
    text: Ubuntu
    code: Ubuntu Mono
  static_templates:
    - 404.html
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep-orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
docs_dir: adhd
nav:
  - index.md
  - ADHS:
    - adhs_was_ist_das.md
    - adhs_symptome.md
    - adhs_spektrum.md
  - Diagnose:
    - diagnose_rechtliches.md
    - diagnose_bestandteile.md
    - diagnose_testverfahren.md
    - diagnose_ablauf.md
    - diagnose_anlaufstellen.md
    - diagnose_sorgen.md
    - diagnose_danach.md 
  - Behandlung:
    - behandlung_therapieansätze.md
    - behandlung_medikamente.md
  - Sonstiges:
    - sonstiges_tips.md
    - sonstiges_quellen.md

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - markdown.extensions.nl2br
  - attr_list
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "_"
