site_name: ADHD Info Dump
site_description: ADHD Info Dump
site_author: polite raccoon
site_url: https://polite-raccoon.github.io/adhd-info-dump/
repo_name: 'polite-raccoon/adhd-info-dump'
repo_url: 'https://github.com/polite-raccoon/adhd-info-dump'
theme:
  features:
    - tabs
    - navigation.expand
    - navigation.sections
  name: material
  icon:
    logo: material/cloud
  font:
    text: Ubuntu
    code: Ubuntu Mono
  static_templates:
    - 404.html
  palette:
    scheme: slate
    primary: teal
docs_dir: adhd

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "_"
